#ifndef DARMOK_SAMPLERS_HEADER
#define DARMOK_SAMPLERS_HEADER

// shared

#define DARMOK_SAMPLER_MATERIAL_ALBEDO_LUT 0

#define DARMOK_SAMPLER_MATERIAL_BASECOLOR 1
#define DARMOK_SAMPLER_MATERIAL_SPECULAR 2
#define DARMOK_SAMPLER_MATERIAL_METALLIC_ROUGHNESS 3
#define DARMOK_SAMPLER_MATERIAL_NORMAL 4
#define DARMOK_SAMPLER_MATERIAL_OCCLUSION 5
#define DARMOK_SAMPLER_MATERIAL_EMISSIVE 6

#define DARMOK_SAMPLER_LIGHTS_POINTLIGHTS 7

// per renderer

#define DARMOK_SAMPLER_CLUSTERS_CLUSTERS 8
#define DARMOK_SAMPLER_CLUSTERS_LIGHTINDICES 9
#define DARMOK_SAMPLER_CLUSTERS_LIGHTGRID 10
#define DARMOK_SAMPLER_CLUSTERS_ATOMICINDEX 11

#define DARMOK_SAMPLER_DEFERRED_DIFFUSE_A 8
#define DARMOK_SAMPLER_DEFERRED_NORMAL 9
#define DARMOK_SAMPLER_DEFERRED_F0_METALLIC 10
#define DARMOK_SAMPLER_DEFERRED_EMISSIVE_OCCLUSION 11
#define DARMOK_SAMPLER_DEFERRED_DEPTH 12

#endif // DARMOK_SAMPLERS_HEADER
