# vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO miguelibero/darmok
  REF "v${VERSION}"
  SHA512 ade545aca81bf16b4336d9f76ef7b2ca4889ef0a4950073b5ad127fcb6fb18324eadd5b5bab34493062741937c8900eadd1e0614e2f9f714565037e61aab18a2
)

vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    DARMOK_BUILD_SAMPLES=OFF
    DARMOK_BUILD_TESTS=OFF
    DARMOK_BUILD_LUA=ON
    DARMOK_BUILD_LUA_EXE=ON
    DARMOK_BUILD_IMGUI=ON
    DARMOK_BUILD_RMLUI=ON
    DARMOK_BUILD_ASSIMP=ON
    DARMOK_BUILD_OZZ=ON
    DARMOK_BUILD_JOLT=ON
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
  file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()

file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
configure_file("${CMAKE_CURRENT_LIST_DIR}/usage.txt" "${CURRENT_PACKAGES_DIR}/share/${PORT}/usage" COPYONLY)

