# vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO miguelibero/darmok
  REF "v${VERSION}"
  SHA512 983aab89f22b3a567b81d00e095a52a6caad0076db243c9a0907383016ed10d2aeecb15b292eebed2358406dc192a6270f9b87f50de5ff37e1822c2f88941b0d
)

vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    DARMOK_BUILD_SAMPLES=OFF
    DARMOK_BUILD_TESTS=OFF
    DARMOK_BUILD_LUA=ON
    DARMOK_BUILD_LUA_EXE=ON
    DARMOK_BUILD_IMGUI=ON
    DARMOK_BUILD_RMLUI=ON
    DARMOK_BUILD_ASSIMP=ON
    DARMOK_BUILD_OZZ=ON
    DARMOK_BUILD_JOLT=ON
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
  file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()

file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
configure_file("${CMAKE_CURRENT_LIST_DIR}/usage.txt" "${CURRENT_PACKAGES_DIR}/share/${PORT}/usage" COPYONLY)

